# Makefile for Borland C

PRJDIR          = ../..

!include $(PRJDIR)/Bcc.inc

CFLAGS          = $(CFLAGS) -DINDEXLIB -DMLH_MAP -DSDK

OBJECTS       = asdata.obj asexpr.obj aslex.obj aslist.obj asmain.obj \
                asout.obj assubr.obj z80adr.obj z80ext.obj \
                z80mch.obj z80pst.obj \
                ../asxxsrc/strcmpi.obj ../asxxsrc/assym.obj

TARGET         = $(PRJDIR)/bin/as-z80.exe

all: $(TARGET)

$(TARGET): $(OBJECTS)
        $(CC) $(CFLAGS) -e$@ $(OBJECTS)
