/* Register definitions for pic16f639.
 * This file was automatically generated by:
 *   inc2h.pl V1.6
 *   Copyright (c) 2002, Kevin L. Pauba, All Rights Reserved
 */
#include <pic16f639.h>

data __at (INDF_ADDR) volatile char      INDF;
sfr  __at (TMR0_ADDR)                    TMR0;
data __at (PCL_ADDR) volatile char       PCL;
sfr  __at (STATUS_ADDR)                  STATUS;
sfr  __at (FSR_ADDR)                     FSR;
sfr  __at (PORTA_ADDR)                   PORTA;
sfr  __at (PORTC_ADDR)                   PORTC;
sfr  __at (PCLATH_ADDR)                  PCLATH;
sfr  __at (INTCON_ADDR)                  INTCON;
sfr  __at (PIR1_ADDR)                    PIR1;
sfr  __at (TMR1L_ADDR)                   TMR1L;
sfr  __at (TMR1H_ADDR)                   TMR1H;
sfr  __at (T1CON_ADDR)                   T1CON;
sfr  __at (WDTCON_ADDR)                  WDTCON;
sfr  __at (CMCON0_ADDR)                  CMCON0;
sfr  __at (CMCON1_ADDR)                  CMCON1;
sfr  __at (OPTION_REG_ADDR)              OPTION_REG;
sfr  __at (TRISA_ADDR)                   TRISA;
sfr  __at (TRISC_ADDR)                   TRISC;
sfr  __at (PIE1_ADDR)                    PIE1;
sfr  __at (PCON_ADDR)                    PCON;
sfr  __at (OSCCON_ADDR)                  OSCCON;
sfr  __at (OSCTUNE_ADDR)                 OSCTUNE;
sfr  __at (LVDCON_ADDR)                  LVDCON;
sfr  __at (WPUDA_ADDR)                   WPUDA;
sfr  __at (IOCA_ADDR)                    IOCA;
sfr  __at (WDA_ADDR)                     WDA;
sfr  __at (VRCON_ADDR)                   VRCON;
sfr  __at (EEDAT_ADDR)                   EEDAT;
sfr  __at (EEDATA_ADDR)                  EEDATA;
sfr  __at (EEADR_ADDR)                   EEADR;
sfr  __at (EECON1_ADDR)                  EECON1;
sfr  __at (EECON2_ADDR)                  EECON2;
sfr  __at (CRCON_ADDR)                   CRCON;
sfr  __at (CRDAT0_ADDR)                  CRDAT0;
sfr  __at (CRDAT1_ADDR)                  CRDAT1;
sfr  __at (CRDAT2_ADDR)                  CRDAT2;
sfr  __at (CRDAT3_ADDR)                  CRDAT3;

// 
// bitfield definitions
// 
volatile __CMCON0_bits_t __at(CMCON0_ADDR) CMCON0_bits;
volatile __CMCON1_bits_t __at(CMCON1_ADDR) CMCON1_bits;
volatile __INTCON_bits_t __at(INTCON_ADDR) INTCON_bits;
volatile __OPTION_REG_bits_t __at(OPTION_REG_ADDR) OPTION_REG_bits;
volatile __OSCCON_bits_t __at(OSCCON_ADDR) OSCCON_bits;
volatile __OSCTUNE_bits_t __at(OSCTUNE_ADDR) OSCTUNE_bits;
volatile __PCON_bits_t __at(PCON_ADDR) PCON_bits;
volatile __PIE1_bits_t __at(PIE1_ADDR) PIE1_bits;
volatile __PIR1_bits_t __at(PIR1_ADDR) PIR1_bits;
volatile __STATUS_bits_t __at(STATUS_ADDR) STATUS_bits;
volatile __T1CON_bits_t __at(T1CON_ADDR) T1CON_bits;
volatile __WDTCON_bits_t __at(WDTCON_ADDR) WDTCON_bits;

