/* WORK IN PROGRESS: do not watch this if you don't have the legal
   age in your country to watch this.
*/

/* This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/* This is a cheap hack. The xa51 has a couple of ways to scramble
   relocation info into it's opcode that the standard linker can't
   handle. 

   The relocatable format looks like the known one, BUT ISN'T.

   The only things that are handled now are:

   "SDCCXA rel, version %f" must be the first line, sort of MAGIC word
   "H %d areas %d global symbols" defines the # of areas and globals
   "S <symbol> [Ref0000 | DefXXXX]" Def's are supposed to be defined in
     their own area/segment
   "A <seg> size %d flags %d" switch to another segment. this can happen
     multiple times and should be equal. flags is ignored for now
   "T xx xx bb bb ..." where xx xx is the address within the current segment
     and bb are the bytes
   "R xx <how> <symbol>" the relocation info. xx is the offset within the
     previous "T .." line. <how> could be something like REL_FF, REL_FFFF, 
     ABS_F0FF. symbol is the (previous) defined symbol it refers to

   So, this is not a standalone linker. It will only link files generated
   by xa_asm, which will only process files generated by the xa51 sdcc
   port.
*/

#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <string.h>

#include "xa_version.h"

enum {
  // these are all concatenated into the code image
  GSINIT=1,
  CSEG,
  XINIT,
  //GSFINAL, // do we need this?

  // these are only for storage
  BSEG,
  DSEG,
  XSEG,
  XISEG,
  MAX_SEGMENTS
};

#define CODESIZE 0x10000

char codeImage[CODESIZE];
char gsinitImage[CODESIZE];
char xinitImage[CODESIZE];

struct SEGMENT {
  short id;
  char *name;
  int hasSymbols;
  int _size;
  int start;
  int current;
  unsigned char *image;
} segments[MAX_SEGMENTS]={
  {0,       "????",    0, 0, 0, 0, NULL},

  {GSINIT,  "GSINIT",  0, 0, 0, 0, gsinitImage},
  {CSEG,    "CSEG",    0, 0, 0, 0, codeImage},
  {XINIT,   "XINIT",   0, 0, 0, 0, xinitImage},
  //{GSFINAL, "GSFINAL", 0, 0, 0, 0, NULL},

  {BSEG,    "BSEG",    0, 0, 0, 0, NULL},
  {DSEG,    "DSEG",    0, 0, 0, 0, NULL},
  {XSEG,    "XSEG",    0, 0, 0, 0, NULL},
  {XISEG,   "XISEG",   0, 0, 0, 0, NULL},
};

struct MODULE {
  char *name;
  int offset[MAX_SEGMENTS];
  int size[MAX_SEGMENTS];
  struct MODULE *next;
  struct MODULE *last;
} *modules=NULL;


struct SYMBOL {
  char *name;
  struct MODULE *module;
  struct SEGMENT *segment;
  int address;
  struct SYMBOL *next;
  struct SYMBOL *last;
} *symbols=NULL;

char *libPaths[128];
int nlibPaths=0;
char *libFiles[128];
int nlibFiles=0;

static char outFileName[PATH_MAX];

struct SEGMENT *currentSegment;
struct MODULE *currentModule;

struct SEGMENT *findSegment(char *segment) {
  int i;
  for (i=1; i<MAX_SEGMENTS; i++) {
    if (strcmp(segments[i].name, segment)==0) {
      return &segments[i];
    }
  }
  return 0;
}

void addToModules (char *name) {
  struct MODULE *module;
  int s;

  //fprintf (stderr, "addToModules: %s\n", name);

  module=calloc(1, sizeof(struct MODULE));
  module->name=strdup(name);
  for (s=0; s<MAX_SEGMENTS; s++) {
    module->offset[s]=segments[s].current;
  }
  if (!modules) {
    modules=module;
  } else {
    modules->last->next=module;
  }
  currentModule=modules->last=module;
}

void addToRefs(char *ref) {
  //fprintf (stderr, "addToRefs: %s\n", ref);
}

void addToDefs(char *def, int address) {
  struct SYMBOL *symbol;
  /* fprintf (stderr, "addToDefs: %s %s 0x%04x + 0x%04x\n", 
     currentSegment->name, def, 
     currentModule->offset[currentSegment->id],
     address); */
  symbol=calloc(1, sizeof(struct SYMBOL));
  symbol->name=strdup(def);
  symbol->module=currentModule;
  symbol->segment=currentSegment;
  symbol->address=currentModule->offset[currentSegment->id]+address;
  if (!symbols) {
    symbols=symbol;
  } else {
    symbols->last->next=symbol;
  }
  symbols->last=symbol;
  currentSegment->hasSymbols++;
}

void syntaxError (char *err) {
  fprintf (stderr, "error while parsing '%s'\n", err);
  exit(1);
}

void baseName(char *name, char*base) {
  int i, first, last;

  // find the last path seperator in name
  for (first=strlen(name)-1; 
       (name[first]!='/' && name[first]!='\\') && first;
       first--);
  if (name[first]=='/' || name[first]=='\\') {
    first++;
  }

  // find the last ext seperator in name
  for (last=strlen(name)-1; 
       (name[last]!='.' && last);
       last--);
  if (!last) {
    last=strlen(name);
  }

  fprintf (stderr, "baseName: %s %d %d\n", name, first, last);
  // fill the base with the baseName
  for (i=first; i<last; i++) {
    base[i-first]=name[i];
  }
  base[i]='\0';
}
  
void readModule(char *module) {
  double hisVersion;
  char line[132];
  FILE *relModule;
  char moduleName[PATH_MAX];
  int segments, globals;
  int currentLine=1;

  if ((relModule=fopen(module, "r"))==NULL) {
    perror (module);
    exit (1);
  }

  //fprintf (stderr, "ReadModule: %s\n", module);

  // first we need to check if this is a valid file
  if (sscanf(fgets(line, 132, relModule), 
	     "SDCCXA rel, version %lf", &hisVersion)!=1) {
    fprintf (stderr, "%s is not a valid input file\n", module);
    exit (1);
  }
  if (hisVersion!=version) {
    fprintf (stderr, "WARNING: version conflict; "
	     "we(%1.1f) != %s(%1.1f)\n", 
	     version, module, hisVersion);
  }
  currentLine++;
  
  // H 7 areas 168 global symbols
  if (sscanf(fgets(line, 132, relModule),
	     "H %d areas %d global symbols",
	     &segments, &globals)!=2) {
    syntaxError(line);
  }
  currentLine++;

  // M module
  if (sscanf(fgets(line, 132, relModule),
	     "M %s", moduleName)!=1) {
    syntaxError(line);
  }

  // add this to the known modules with current offsets
  addToModules(module);

  fprintf (stderr, "module %s has %d segment%s and %d globals\n",
	   moduleName, segments, segments==1?"":"s", globals);
  currentLine++;

  // now for the ASTR tags
  while (fgets(line, 132, relModule)) {
    switch (line[0]) 
      {
      case 'A': {
	char segment[32];
	int size, flags;
	if (sscanf(line, "A %[^ ] size %d flags %d",
		   segment, &size, &flags)!=3) {
	  fprintf (stderr, "%s:%d error in A record line\n", 
		   module, currentLine);
	  exit (1);
	}
	// do we know this segment?
	if (!(currentSegment=findSegment(segment))) {
	  fprintf (stderr, "%s:%d unknown area: %s\n", module,
		   currentLine, segment);
	  exit (1);
	}
	if (currentModule->size[currentSegment->id]) {
	  if (currentModule->size[currentSegment->id] != size) {
	    fprintf (stderr, "%s:%d error %s %d %d\n",
		     module, currentLine,
		     currentSegment->name,
		     currentModule->size[currentSegment->id], 
		     size);
	  }
	} else {
	  currentModule->size[currentSegment->id]=size;
	  currentModule->offset[currentSegment->id]+=currentSegment->_size;
	  currentSegment->_size += size;
	}
	//fprintf (stderr, "Area: %s size: %d\n", segment, size);
	// never mind about the flags for now
	break;
      }
      case 'S': {
	char symbol[132];
	char refdef[132];
	unsigned int address;
	if (sscanf(line, "S %[^ ] %s", symbol, refdef)!=2) {
	  fprintf (stderr, "%s:%d syntax error near \"%s\"\n",
		   module, currentLine, line);
	  exit (1);
	}
	if (strncmp(refdef, "Ref", 3)==0) {
	  addToRefs(symbol);
	} else if (strncmp(refdef, "Def", 3)==0) {
	  sscanf (refdef, "Def%04x", &address);
	  addToDefs(symbol, address);
	} else {
	  fprintf (stderr, "%s:%d found invalid symbol definition \"%s\"\n", 
		   module, currentLine, line);
	  exit (1);
	}
	break;
      }
      case 'T': {
	unsigned int address;
	unsigned int byte;
	char *tline=NULL;
	if (currentSegment->id!=CSEG && 
	    currentSegment->id!=GSINIT &&
	    //currentSegment->id!=GSFINAL &&
	    currentSegment->id!=XINIT) {
	  fprintf (stderr, "%s:%d cannot emit bytes in %s\n",
		   module, currentLine, currentSegment->name);
	  exit (1);
	}
	if (sscanf(strtok(&line[2], " "), "%04x", &address)!=1) {
	  fprintf (stderr, "%s:%d error in T record\n", module, currentLine);
	  exit (1);
	}
	//fprintf (stderr, "%04x:", address);
	address+=currentSegment->current;
	for ( ;
	      (tline=strtok(NULL, " \t\n")) && 
		(sscanf(tline, "%02x", &byte)==1);
	      ) {
	  //fprintf (stderr, " %02x", byte);
	  currentSegment->image[address++]=byte;
	  currentSegment->current++;
	}
	//fprintf (stderr, "\n");
	break;
      }
      case 'R':
	//fprintf (stderr, "%s", line);
	break;
      default:
	/* fprintf (stderr, "%s:%d unknown record \"%s\"\n",
	   module, currentLine, line); */
	break;
      }
    currentLine++;
  }
  // that's all for now, thanks for watching */
  fclose (relModule);
}

void writeModule() {
  fprintf (stderr, "WriteModule: %s\n", outFileName);
  // oops, forgot something :) */
}

void relocate() {
  struct SYMBOL *symbol;
  int length=segments[GSINIT].current +
    segments[CSEG].current +
    segments[XINIT].current;

  // first check if it will fit
  if (length > 0xffff) {
    fprintf (stderr, "error: code segment exceeds 0xffff\n");
    exit(1);
  }
  fprintf (stderr, "relocate: total code size: 0x%04x\n", length);

  // GSINIT gets the --code-loc
  segments[GSINIT].start=segments[CSEG].start;
  segments[CSEG].start=segments[GSINIT].start+segments[GSINIT]._size;
  segments[XINIT].start=segments[CSEG].start+segments[CSEG]._size;
  segments[XISEG].start=segments[XSEG].start+segments[XINIT]._size;  
  // now relocate the defined symbols
  for (symbol=symbols; symbol; symbol=symbol->next) {
    symbol->address += symbol->segment->start;
  }
}

void usage (char * progName, int errNo) {
  fprintf (stderr, "usage: %s lnkCmdFile\n", progName);
  if (errNo) {
    exit (errNo);
  }
}

int main(int argc, char **argv) {
  FILE *linkCommandsFile;
  char linkCommandsPath[PATH_MAX];
  char linkCommand[PATH_MAX];
  struct MODULE *module;
  struct SYMBOL *symbol;
  int s;

  if (argc!=2) {
    usage(argv[0], 1);
  }

  memset(codeImage, 0xff, CODESIZE);

  // read in the commands
  sprintf (linkCommandsPath, "%s.lnk", argv[1]);
  if (!(linkCommandsFile=fopen(linkCommandsPath, "r"))) {
    perror(linkCommandsPath);
    exit(1);
  }
  while (fgets(linkCommand, PATH_MAX, linkCommandsFile)) {
    linkCommand[strlen(linkCommand)-1]='\0';

    // skip empty lines
    if (!*linkCommand) {
      continue;
    }

    //puts (linkCommand);
    if (*linkCommand=='-') {
      switch (linkCommand[1]) 
	{
	case 'm':
	  // probably -muxi, ignore for now
	  break;
	case 'e':
	  // -e, always in the last line, ignore for now
	  break;
	case 'b': 
	  {
	    // a segment start address like: "-b XSEG = 0x4000"
	    int s;
	    char *seg=strtok(&linkCommand[3], " \t");
	    for (s=0; s<MAX_SEGMENTS; s++) {
	      if (strcmp(segments[s].name, seg)==0) {
		strtok(NULL, " \t"); // skip the '='
		if (sscanf(strtok(NULL, " \t"), "%x", 
			   &segments[s].start)!=1) {
		  syntaxError(linkCommand);
		}
		/* fprintf (stderr, "%s starts at 0x%04x\n", segments[s].name,
		   segments[s].start); */
		break;
	      }
	    }
	    if (s==MAX_SEGMENTS) {
	      syntaxError(linkCommand);
	    }
	  }
	  break;
	case 'k':
	  // a lib path like: "-k /usr/local/share/sdcc/lib/xa51"; one/line
	  libPaths[nlibPaths++]=strdup(&linkCommand[3]);
	  break;
	case 'l':
	  // a lib file like: "-l libsdcc"; one/line
	  libFiles[nlibFiles++]=strdup(&linkCommand[3]);
	  break;
	default:
	  syntaxError(linkCommand);
	}
    } else {
      // not a switch, must be an inputfile; one/line
      readModule(linkCommand);
    }
  }

  relocate();

  // the modules
  for (module=modules; module; module=module->next) {
    fprintf (stderr, "%s: ", module->name);
    for (s=0; s<MAX_SEGMENTS; s++) {
      if (module->size[s]) {
	fprintf (stderr, "%s:0x%04x-0x%04x ", segments[s].name,
		 module->offset[s], module->offset[s]+module->size[s]);
      }
    }
    fprintf (stderr, "\n");
  }

  // the symbols
  for (symbol=symbols; symbol; symbol=symbol->next) {
    fprintf (stderr, "%s %s 0x%04x %s\n", symbol->name, symbol->segment->name,
	     symbol->address, symbol->module->name);
  }

  // the segments
  for (s=1; s<MAX_SEGMENTS; s++) {
    if (segments[s]._size) {
      fprintf (stderr, "%s start 0x%04x size 0x%04x %d symbols\n",
	       segments[s].name, segments[s].start,
	       segments[s]._size, 
	       segments[s].hasSymbols);
    }
  }

  writeModule();
  return 0;
}

