# Makefile for Borland C++

PRJDIR          = ../..

!include $(PRJDIR)/Bcc.inc

LKOBJECTS       = lkmain.obj lkhead.obj lkarea.obj lkdata.obj \
                  lkeval.obj lklex.obj lksym.obj lkrloc.obj \
                  lklibr.obj lklist.obj lkihx.obj lks19.obj \
                  lkstore.obj lknoice.obj lkmem.obj lkaomf51.obj strcmpi.obj

ASLINK          = $(PRJDIR)/bin/aslink.exe

all: $(ASLINK)

$(ASLINK): $(LKOBJECTS)
        $(CC) $(CFLAGS) -e$@ $(LKOBJECTS)
