# Makefile for Borlad C++

PRJDIR          = ../..

!include $(PRJDIR)/Bcc.inc

OBJECTS         = sdcclib.obj

TARGET          = $(PRJDIR)/bin/sdcclib.exe

all: $(TARGET)

$(TARGET): $(OBJECTS)
        $(CC) $(CFLAGS) -e$@ $(OBJECTS)
