#
# Makefile - Makefile to build pic16 local register store/restore
#	     support library
#
# This file is part of the GNU PIC Library.
#
# January, 2004
# The GNU PIC Library is maintained by,
# 	Vangelis Rokas <vrokas@otenet.gr>
#
# $Id$
#
#


SRCS	=	lrst \
		lrrest


include ../Makefile.rules


all: build-library

build-library: $(OFILES)
