#
# Makefile.rules - Common Makefile rules to build pic16 C Library
#
# This file is part of the GNU PIC Library.
#
# January, 2004
# The GNU PIC Library is maintained by,
# 	Vangelis Rokas <vrokas@otenet.gr>
#
# $Id$
#
#


include ../../Makefile.common

PRJDIR	= ../../../../..

LIBC_INC_DIR	= $(PRJDIR)/device/include/pic16

#OPT_FLAGS	+= --pstack-model=large
#OPT_FLAGS	+= --stack-auto

COMPILE_FLAGS	+= $(MODELFLAGS) $(OPT_FLAGS)


CFLAGS	= -I$(LIBC_INC_DIR)

CFILES	= $(patsubst %,%.c,$(SRCS))
COFILES	= $(patsubst %.c,%.o,$(CFILES))

ASFLAGS	= -I$(LIBC_INC_DIR) -p18f452 -D__18F452

SFILES	= $(patsubst %,%.S,$(S_SRCS))
SOFILES	= $(patsubst %.S,%.o,$(SFILES))

OFILES	= $(COFILES) $(SOFILES)

.c.o:
	$(CC) $(CFLAGS) $(COMPILE_FLAGS) -c $<

.S.o:
	$(AS) $(ASFLAGS) -c $<

all: build-library clean-intermediate-no-asm

clean-intermediate:
	$(RM) -f *.lst *.asm *.dump* *.p *.d *.adb

clean-intermediate-no-asm:
	$(RM) -f *.lst *.dump* *.p *.d *.adb


clean: clean-intermediate
	$(RM) -f $(LIB) *.o

dep .depend:
	rm -f .depend
	for temp in $(CFILES); do \
		$(CPP) $(MM) $(CFLAGS) $$temp > .tmpdepend; \
		$(SED) s/.rel/.o/g .tmpdepend >> .depend; \
		$(RM) -f .tmpdepend; \
	done;
	if [ ! -e .depend ]; then touch .depend; fi;

include .depend
