# Makefile for Borland C++

PRJDIR          = ../..

!include $(PRJDIR)/Bcc.inc

ASOBJECTS       = asmain.obj aslex.obj assym.obj assubr.obj asnoice.obj \
                  asexpr.obj asdata.obj aslist.obj asout.obj asstore.obj \
                  i51ext.obj i51pst.obj i51mch.obj i51adr.obj strcmpi.obj

ASX8051         = $(PRJDIR)/bin/asx8051.exe

all: $(ASX8051)

$(ASX8051): $(ASOBJECTS)
        $(CC) $(CFLAGS) -e$@ $(ASOBJECTS)
