PRJDIR = ../..

# !include $(PRJDIR)/Makefile.common

OBJ = gen.obj ralloc.obj main.obj
LIB = port.lib

CFLAGS  = -6 -O -g0 -I.. -I. -I..\.. -I..\..\support

.c.obj:
        BCC32 -c $(CFLAGS) $(CPPFLAGS) $<

all: $(LIB)

main.obj: main.c peeph.rul

$(LIB): peeph.rul $(OBJ)
	del $(LIB)
	tlib /a $(LIB) +gen.obj +ralloc.obj +main.obj
	
peeph.rul: peeph.def
        gawk -f ../SDCCpeeph.awk peeph.def > peeph.rul

# include clean.mk
