#
# Makefile.rules - Common Makefile rules to build pic16 C Library
#
# This file is part of the GNU PIC Library.
#
# January, 2004
# The GNU PIC Library is maintained by,
# 	Vangelis Rokas <vrokas@otenet.gr>
#
# $Id$
#
#


include ../../Makefile.common

PRJDIR	= ../../../../..

LIBC_INC_DIR	= $(PRJDIR)/device/include/pic16

COMPILE_FLAGS	+= $(MODELFLAGS)
COMPILE_FLAGS	+= -p$(MCU)
#COMPILE_FLAGS	+= --pomit-config-words --pomit-ivt
COMPILE_FLAGS	+= --no-peep
COMPILE_FLAGS	+= --i-code-in-asm
CFLAGS	= -I$(LIBC_INC_DIR)

CFILES	= $(patsubst %,%.c,$(SRCS))
OFILES	= $(patsubst %.c,%.o,$(CFILES))

%.o: %.c
	$(CC) $(CFLAGS) $(COMPILE_FLAGS) -c $<

all:
	@echo "Please make target build-mcu-library setting"
	@echo "MCU= to the target device (i.e. MCU=18f452)"


build-mcu-library: build-library clean-intermediate-no-asm

clean-intermediate:
	$(RM) -f *.lst *.asm *.dump* *.p *.d *.adb

clean-intermediate-no-asm:
	$(RM) -f *.lst *.dump* *.p *.d *.adb


clean: clean-intermediate
	$(RM) -f $(LIB) *.o

dep .depend:
	rm -f .depend
	for temp in $(CFILES); do \
		$(CPP) $(MM) $(CFLAGS) $$temp > .tmpdepend; \
		$(SED) s/.rel/.o/g .tmpdepend >> .depend; \
		$(RM) -f .tmpdepend; \
	done;

include .depend
