#
# Makefile.rules - Common Makefile rules to build pic16
#                  debug library
#
# This file is part of the GNU PIC Library.
#
# January, 2004
# The GNU PIC Library is maintained by,
# 	Vangelis Rokas <vrokas@otenet.gr>
#
# $Id$
#
#


include ../../Makefile.common

PRJDIR	= ../../../../..

LIBC_INC_DIR	= $(PRJDIR)/device/include/pic16

COMPILE_FLAGS	+= $(MODELFLAGS) --pomit-config-words --pomit-ivt --no-peep --i-code-in-asm
CFLAGS	= --nostdinc -I$(LIBC_INC_DIR)

CFILES	= $(patsubst %,%.c,$(SRCS))
OFILES	= $(patsubst %.c,%.o,$(CFILES))

%.o: %.c
	$(CC) $(CFLAGS) $(COMPILE_FLAGS) -c $<


all: build-library

clean-intermediate:
	$(RM) -f *.lst *.asm *.dump* *.p *.d *.adb


clean: clean-intermediate
	$(RM) -f $(LIB) *.o

dep .depend:
	rm -f .depend
	for temp in $(CFILES); do \
		$(CPP) $(MM) $(CFLAGS) $$temp > .tmpdepend; \
		$(SED) s/.rel/.o/g .tmpdepend >> .depend; \
		$(RM) -f .tmpdepend; \
	done;

include .depend
