#!/bin/sh
# Script to compile with mingw32
TOOLSPREFIX=/usr/local/cross-tools/i386-mingw32msvc/bin

export CC=$TOOLSPREFIX/gcc
export CXX=$TOOLSPREFIX/g++
export RANLIB=$TOOLSPREFIX/ranlib
export STRIP=$TOOLSPREFIX/strip

export SDCCCONFIGUREFLAGS="--prefix=/sdcc --disable-device-lib-build \
--disable-ucsim --program-suffix=.exe --datadir=/sdcc \
--host=i586-mingw32msvc --build=unknown-unknown-linux-gnu"

./configure $SDCCCONFIGUREFLAGS
make 2>&1 | tee make.log



