#!/bin/sh
# Script to "cross" compile with mingw32 under Cygwin

./configure -C \
--prefix="/sdcc" \
--datadir="/sdcc" \
docdir="/sdcc/doc" \
include_dir_suffix="include" \
lib_dir_suffix="lib" \
sdccconf_h_dir_separator="\\\\" \
CC="gcc -mno-cygwin" \
CXX="g++ -mno-cygwin"

make 2>&1 | tee make.log
