#
# Makefile - Makefile to build pic16 stack tracing support function
#
# This file is part of the GNU PIC Library.
#
# January, 2004
# The GNU PIC Library is maintained by,
# 	Vangelis Rokas <vrokas@otenet.gr>
#
# $Id$
#
#


SRCS	=	gstack


include ../Makefile.rules


all: build-library

build-library: $(OFILES)
