#
# Makefile.rules - Common Makefile rules to build pic16
#                  support libraries
#
# This file is part of the GNU PIC Library.
#
# January, 2004
# The GNU PIC Library is maintained by,
# 	Vangelis Rokas <vrokas@otenet.gr>
#
# $Id$
#
#


include ../../Makefile.common

PRJDIR	= ../../../../..

LIBC_INC_DIR	= $(PRJDIR)/device/include/pic16

DEBUG	=

OPT_FLAGS	+= --optimize-cmp
#OPT_FLAGS	+= --stack-auto

COMPILE_FLAGS	+= $(MODELFLAGS)
COMPILE_FLAGS   += $(OPT_FLAGS) $(DEBUG)
COMPILE_FLAGS   += $(CSTD)

CPPFLAGS        := -nostdinc $(CFLAGS) -I$(LIBC_INC_DIR)

CFLAGS	+= --nostdinc -I$(LIBC_INC_DIR)


CFILES	= $(patsubst %,%.c,$(SRCS))
COFILES	= $(patsubst %.c,%.o,$(CFILES))

SFILES	= $(patsubst %,%.S,$(AS_SRCS))
SOFILES	= $(patsubst %.S,%.o,$(SFILES))

OFILES	= $(COFILES) $(SOFILES)

%.o: %.c
	$(CC) $(CFLAGS) $(COMPILE_FLAGS) -c $<

.S.o:
	$(AS) -I $(LIBC_INC_DIR) -c $<


all: build-library clean-intermediate-no-asm

clean-intermediate:
	$(RM) -f *.lst *.asm *.dump* *.p *.d *.adb

clean-intermediate-no-asm:
	$(RM) -f *.lst *.dump* *.p *.d *.adb

clean: clean-intermediate
	$(RM) -f $(LIB) *.o

dep .depend:
	rm -f .depend
	for temp in $(CFILES); do \
		$(CPP) $(MM) $(CPPFLAGS) $$temp > .tmpdepend; \
		$(SED) s/.rel/.o/g .tmpdepend >> .depend; \
		$(RM) -f .tmpdepend; \
	done;
	if [ ! -e .depend ]; then touch .depend ; fi ;
include .depend
