

YACC=bison
CC=gcc
LEX=flex
TARGETS=$(SDCCDIR)/bin/sdcpp
STD_INC=$(SDCCDIR)/sdcc51inc
CFLAGS=-I . -DSTANDARD_INCLUDE_DIR='"$(STD_INC)"'  -O2
ALLOBJECTS=cppalloc.o  cpperror.o  cppexp.o    cpphash.o   cpplib.o    cppmain.o 
all: $(TARGETS)

${TARGETS}: ${ALLOBJECTS}
	${CC} ${CFLAGS} ${LDFLAGS} -o $@ ${ALLOBJECTS}

