# Makefile for Borland C++

PRJDIR = ../..

OBJ = gen.obj ralloc.obj main.obj support.obj peep.obj
LIB = port.lib

!include $(PRJDIR)/Bcc.inc
CFLAGS = $(CFLAGS) -I.. -I$(PRJDIR)

all: $(LIB)

main.obj: main.c peeph.rul peeph-z80.rul peeph-gbz80.rul

$(LIB): $(OBJ)
        if exist $(LIB) del $(LIB)
        tlib $@ @&&!
+$(**: = &^
+)
!

.def.rul:
        gawk -f ../SDCCpeeph.awk $< > $@
