# Makefile for Borlad C++

PRJDIR          = ..

!include $(PRJDIR)/Bcc.inc

OBJECTS         = packihx.obj

TARGET          = $(PRJDIR)/bin/packihx.exe

all: $(TARGET)

$(TARGET): $(OBJECTS)
        $(CC) $(CFLAGS) -e$@ $(OBJECTS)
