# Makefile for Borlad C++

PRJDIR          = ../..

!include $(PRJDIR)/Bcc.inc

ASOBJECTS       = asmain.obj aslex.obj assym.obj assubr.obj asnoice.obj \
                  asexpr.obj asdata.obj aslist.obj asout.obj asstore.obj \
                  h08ext.obj h08pst.obj h08mch.obj h08adr.obj \
                  ../strcmpi.obj

ASX8051         = $(PRJDIR)/bin/asx8051.exe

all: $(ASX8051)

$(ASX8051): $(ASOBJECTS)
        $(CC) $(CFLAGS) -e$@ $(ASOBJECTS)
