# Makefile for Borlad C++

PRJDIR = ../..

OBJ = i186.obj ralloc.obj gen.obj tlcs900h.obj gen_generic.obj aop.obj util.obj
LIB = port.lib

!include $(PRJDIR)/Bcc.inc
CFLAGS = $(CFLAGS) -I.. -I$(PRJDIR)

all: $(LIB)

i186.obj: i186.c i186_mappings.i

$(LIB): $(OBJ)
        if exist $(LIB) del $(LIB)
        tlib $@ @&&!
+$(**: = &^
+)
!

.def.rul:
        gawk -f ../SDCCpeeph.awk $< > $@
