#
# Makefile - Makefile to build pic16 generic pointer support library
#
# This file is part of the GNU PIC Library.
#
# January, 2004
# The GNU PIC Library is maintained by,
# 	Vangelis Rokas <vrokas@otenet.gr>
#
# $Id$
#
#


SRCS	=	gptrget1 \
		gptrget2 \
		gptrget3 \
		gptrget4 \
		gptrput1 \
		gptrput2 \
		gptrput3 \
		gptrput4
		

include ../Makefile.rules

all: build-library

build-library: $(OFILES)
#	@$(CP) -v $(OFILES) ../../bin
