# Makefile for Borlad C++

PRJDIR = ../..

OBJ = gen.obj genarith.obj ralloc.obj main.obj glue.obj pcode.obj pcodepeep.obj graph.obj
LIB = port.lib

!include $(PRJDIR)/Bcc.inc
CFLAGS = $(CFLAGS) -I.. -I$(PRJDIR)

all: $(LIB)

main.obj: main.c peeph.rul

$(LIB): $(OBJ)
        if exist $(LIB) del $(LIB)
        tlib $@ @&&!
+$(**: = &^
+)
!

.def.rul:
        gawk -f ../SDCCpeeph.awk $< > $@
